### ISSUE TITLE
Resource bar

### ISSUE THREAD

**Issue by cmgangrel** [nmsmith22389/CandyUI#24]
Does not save position between logins.

**Comment by nmsmith22389** [comment]
I just fixed this. I can't remember if I committed it though so I'll double check just in case.

**Comment by ZataH** [comment]
This is still a problem, or do I need to delete some save files?
