### ISSUE TITLE
CandyUI_Datachron

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#37]
Error popped up on my engy when I got a quest

...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:292: bad argument #1 to 'QueueNextCall' (number expected, got nil)
stack trace:
    [C]: in function 'QueueNextCall'
    ...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:292: in function <...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:287>

Also, the graphics are kinda goofy on the datachron now that it's anchored to the minimap. My scientist bot info is under the actual datachron, and it covers the quest helper so you cant really leave it open if you want to.

**Comment by nmsmith22389** [comment]
Yeah I'm trying to figure out a way to make it less obtrusive. Any ideas
you have would be great

**Comment by ZataH** [comment]
Can you make the datachron movable?

**Comment by cmgangrel** [comment]
Got the same error after handing in my daily crafting quest in Thayd. This error cropped up about 5 seconds later.

**Comment by nmsmith22389** [comment]
I'm also working on making a new minimap because the stock one is sort of tied into the datachron

**Comment by Mae-Is-Mean** [comment]
The datachron isn't spitting errors anymore, but it does still not look right for scientists. The bot info is not in the right spot and ends up off-frame.

**Comment by Mae-Is-Mean** [comment]
Newest update (10/31) still has the scientist graphic bug. The datachron doesn't seem to be linked to the minimap anymore and is back on the bottom (and moveable, which is nice) so I hope that was intended =)
![scibot](https://cloud.githubusercontent.com/assets/8868659/4869090/d659a08c-6147-11e4-9e78-6b5a1c9d1fd0.jpg)

**Comment by nmsmith22389** [comment]
That is a very weird bug. I will have to look into it, and yes it being movable was intentional. Thanks!

**Comment by nmsmith22389** [comment]
Fixed the scientist problem in the next update! Thanks!

**Comment by Mae-Is-Mean** [comment]
This is not fixed on the update posted 11/28. I tried the files here and the ones on Curse, both still have this same bug.

**Comment by nmsmith22389** [comment]
maybe i got the files mixed up with an older version

ill double check everything and fix the problems if i need to . Thanks!
